#!/bin/sh
# worker_v1 entrypoint. Two-phase script:
#
#   Phase 1 (root): validate env, write
#       ~/.claude/.credentials.json, seed onboarding state in
#       ~/.claude.json + ~/.claude/settings.json, chown
#       /workspace + ~worker so the bind mount and config files
#       are writable by the worker user, then re-exec self under
#       gosu as `worker`.
#
#   Phase 2 (worker): cd /workspace, optional repo clone, optional
#       .mcp.json write for clawborrator integration, exec claude
#       with the right flag set.
#
# Why two phases:
#   - Claude Code's --dangerously-skip-permissions refuses to run
#     as root.
#   - Bind-mounted /workspace can arrive owned by a uid the worker
#     user can't write to (Docker creates the dir as root if it
#     didn't exist on the host).
#
# Idempotent on restart: priv'd writes overwrite, clone skips if
# .git is already present. The actual workspace state (CC's
# persisted session, .claude/clawborrator/identity.json, uncommitted
# edits) survives across restarts via the /workspace volume.

set -e

WORKER_USER="worker"
WORKER_HOME="/home/${WORKER_USER}"

# ════════════════════════════════════════════════════════════════
# Phase 1 — root setup
# ════════════════════════════════════════════════════════════════
if [ "$(id -u)" = "0" ]; then

  # ─── Required env ──────────────────────────────────────────────
  # Three accepted auth credentials, evaluated as a strict
  # first-match-wins fallback chain:
  #
  #   1. ANTHROPIC_API_KEY        — sk-ant-api03-… raw API key.
  #      Claude Code reads it directly from env; no
  #      .credentials.json needed. Bills against the API account
  #      (NOT the Max subscription). Channels work (verified on
  #      Claude Code 2.1.195). Claude asks "Detected a custom API
  #      key, use it?" on first run; the approval is pre-seeded
  #      into ~/.claude.json below so the prompt never shows.
  #
  #   2. CLAUDE_CODE_OAUTH_TOKEN  — sk-ant-oat01-… OAuth access
  #      token. Produced by `claude setup-token` on a logged-in
  #      machine. Claude Code reads it directly from env; no
  #      .credentials.json seeding needed. Bills against the Max
  #      subscription. **Preferred OAuth path** — channels work,
  #      no on-disk credentials state.
  #
  #   3. ANTHROPIC_ACCESS_TOKEN   — sk-ant-oat01-… OAuth access
  #      token from a Claude Max account. Legacy path: worker
  #      seeds ~/.claude/.credentials.json from env on first
  #      boot; claude refreshes the token chain itself thereafter
  #      via the persisted volume. Use only when
  #      CLAUDE_CODE_OAUTH_TOKEN isn't available (e.g. you
  #      already extracted just the access-token field from
  #      a local install).
  #
  # The previous "hybrid" mode (API key + ANTHROPIC_ACCESS_TOKEN
  # both set, to keep channels working under API-key billing) is
  # obsolete — CLAUDE_CODE_OAUTH_TOKEN gives you channels +
  # Max-billed inference natively without the .credentials.json
  # hack. Multi-env collisions now resolve to first-match-wins.
  CREDS_DIR="${WORKER_HOME}/.claude"
  CREDS_FILE="${CREDS_DIR}/.credentials.json"
  GLOBAL_CFG="${WORKER_HOME}/.claude.json"
  SETTINGS_FILE="${CREDS_DIR}/settings.json"
  mkdir -p "${CREDS_DIR}"

  if [ -z "${ANTHROPIC_API_KEY:-}" ] && [ -z "${CLAUDE_CODE_OAUTH_TOKEN:-}" ] && [ -z "${ANTHROPIC_ACCESS_TOKEN:-}" ]; then
    echo "[worker] one of ANTHROPIC_API_KEY, CLAUDE_CODE_OAUTH_TOKEN, or ANTHROPIC_ACCESS_TOKEN is required" >&2
    echo "         API key:                set ANTHROPIC_API_KEY=sk-ant-api03-…" >&2
    echo "         OAuth (preferred):      set CLAUDE_CODE_OAUTH_TOKEN=sk-ant-oat01-…" >&2
    echo "                                 (run \`claude setup-token\` on a logged-in machine)" >&2
    echo "         OAuth (legacy):         set ANTHROPIC_ACCESS_TOKEN=sk-ant-oat01-…" >&2
    echo "                                 (seeds ~/.claude/.credentials.json on first boot)" >&2
    exit 1
  fi

  # ─── Spawn-env snapshot ───────────────────────────────────────
  # Persist the auth + hub + repo env vars to a file before we run
  # the auth-resolution branch below (which `unset`s the losers).
  # spawn-worker.sh sources this file at runtime when constructing
  # `docker run -e …` flags for sibling containers.
  #
  # Why a file: Claude Code redacts ANTHROPIC_* / CLAUDE_CODE_* env
  # vars from Bash-tool subprocesses to prevent the model from
  # accidentally leaking them in tool output. That redaction also
  # hides them from spawn-worker, which is fine when spawn-worker
  # is called from a CC Bash tool — except that spawn-worker NEEDS
  # those values to forward to the child container. Sourcing a
  # file owned by root:worker, mode 0640, sidesteps the env-strip
  # without leaking via env. The agent can still `cat` the file if
  # it explicitly tries — that's the same trust boundary as today
  # (everything's already in the same container).
  mkdir -p /etc/clawborrator
  {
    echo "# Generated by worker_v1 entrypoint at boot. Sourced by"
    echo "# spawn-worker.sh to forward auth + hub + repo env to child"
    echo "# containers. Do NOT edit by hand — regenerated on restart."
    echo "CLAWBORRATOR_TOKEN=${CLAWBORRATOR_TOKEN:-}"
    echo "CLAWBORRATOR_HUB_URL=${CLAWBORRATOR_HUB_URL:-wss://next.clawborrator.com}"
    echo "ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}"
    echo "CLAUDE_CODE_OAUTH_TOKEN=${CLAUDE_CODE_OAUTH_TOKEN:-}"
    echo "ANTHROPIC_ACCESS_TOKEN=${ANTHROPIC_ACCESS_TOKEN:-}"
    echo "ANTHROPIC_REFRESH_TOKEN=${ANTHROPIC_REFRESH_TOKEN:-}"
    echo "ANTHROPIC_TOKEN_EXPIRES_AT=${ANTHROPIC_TOKEN_EXPIRES_AT:-}"
    echo "ANTHROPIC_SUBSCRIPTION_TYPE=${ANTHROPIC_SUBSCRIPTION_TYPE:-max}"
    echo "ANTHROPIC_RATE_LIMIT_TIER=${ANTHROPIC_RATE_LIMIT_TIER:-default_claude_max_20x}"
    echo "REPO_URL=${REPO_URL:-}"
    echo "REPO_REF=${REPO_REF:-}"
    echo "REPO_DIR_NAME=${REPO_DIR_NAME:-repo}"
    echo "REPO_PAT=${REPO_PAT:-}"
    echo "REPO_PAT_USER=${REPO_PAT_USER:-x-access-token}"
    echo "GIT_USER_EMAIL=${GIT_USER_EMAIL:-}"
    echo "GIT_USER_NAME=${GIT_USER_NAME:-}"
    echo "MODEL=${MODEL:-haiku}"
    echo "CLAUDE_SKIP_PERMISSIONS=${CLAUDE_SKIP_PERMISSIONS:-0}"
  } > /etc/clawborrator/spawn-env.conf
  chown root:worker /etc/clawborrator/spawn-env.conf
  chmod 0640        /etc/clawborrator/spawn-env.conf
  echo "[worker] wrote /etc/clawborrator/spawn-env.conf (sourced by spawn-worker)"

  # Resolve which auth path wins. First-match-wins; lower-priority
  # envs are unset so claude's downstream lookup never sees them and
  # logs aren't ambiguous about which path is in play.
  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    unset CLAUDE_CODE_OAUTH_TOKEN ANTHROPIC_ACCESS_TOKEN ANTHROPIC_REFRESH_TOKEN
    echo "[worker] ANTHROPIC_API_KEY set — claude reads it directly from env (bills against API account)"
  elif [ -n "${CLAUDE_CODE_OAUTH_TOKEN:-}" ]; then
    unset ANTHROPIC_ACCESS_TOKEN ANTHROPIC_REFRESH_TOKEN
    echo "[worker] CLAUDE_CODE_OAUTH_TOKEN set — claude reads it directly from env (Max subscription, channels work)"
  else
    # ANTHROPIC_ACCESS_TOKEN path (must be set if we got here — the
    # require-at-least-one check above guarantees it). Seed the
    # claudeAiOauth credentials.json the way `claude` would after an
    # interactive OAuth login.
    #
    # First-boot seed only — when ${WORKER_HOME}/.claude is a docker
    # named volume, the file survives container restart. Claude Code
    # rewrites .credentials.json itself whenever it refreshes the
    # OAuth token chain; overwriting on every boot would destroy the
    # freshly-refreshed credentials.
    #
    # Defaults:
    #   - refreshToken: empty. Without it, no auto-renewal.
    #   - expiresAt: 9999999999999 (far future) so claude doesn't
    #     proactively refresh on a stale-looking timestamp.
    #   - scopes: the full Claude-Code-issued set.
    #   - subscriptionType + rateLimitTier: match Claude Max.
    echo "[worker] ANTHROPIC_ACCESS_TOKEN set — using legacy credentials.json seed path"
    echo "[worker] consider switching to CLAUDE_CODE_OAUTH_TOKEN (run \`claude setup-token\` to get one — Claude reads it directly from env without the .credentials.json hack)"
    if [ -f "${CREDS_FILE}" ]; then
      echo "[worker] ${CREDS_FILE} already present — keeping (worker maintains its own OAuth chain)"
    else
      jq -n \
        --arg at   "${ANTHROPIC_ACCESS_TOKEN}" \
        --arg rt   "${ANTHROPIC_REFRESH_TOKEN:-}" \
        --argjson exp "${ANTHROPIC_TOKEN_EXPIRES_AT:-9999999999999}" \
        --arg sub  "${ANTHROPIC_SUBSCRIPTION_TYPE:-max}" \
        --arg tier "${ANTHROPIC_RATE_LIMIT_TIER:-default_claude_max_20x}" \
        '{
          claudeAiOauth: {
            accessToken:      $at,
            refreshToken:     $rt,
            expiresAt:        $exp,
            scopes: [
              "user:file_upload",
              "user:inference",
              "user:mcp_servers",
              "user:profile",
              "user:sessions:claude_code"
            ],
            subscriptionType: $sub,
            rateLimitTier:    $tier
          }
        }' > "${CREDS_FILE}"
      chmod 600 "${CREDS_FILE}"
      echo "[worker] seeded ${CREDS_FILE} from env (claudeAiOauth, subscription=${ANTHROPIC_SUBSCRIPTION_TYPE:-max})"
    fi
  fi

  # ─── Pre-seed Claude Code onboarding state (first boot only) ───
  # A headless worker can't answer first-run prompts. Pre-write the
  # global ~/.claude.json with the keys that skip every interactive
  # bootstrap step: welcome flow, theme picker, "trust this folder?",
  # CLAUDE.md external-includes warning, bypass-permissions warning,
  # MCP-server approval. Keys extracted from a known-good local
  # install. First-boot-only because claude itself updates this file
  # over time (recent dirs, per-project state) and we don't want to
  # clobber that on restart.
  NOW_ISO=$(date -u +"%Y-%m-%dT%H:%M:%S.000Z")
  if [ -f "${GLOBAL_CFG}" ]; then
    echo "[worker] ${GLOBAL_CFG} already present — keeping (claude maintains project state)"
  else
    jq -n \
      --arg now "${NOW_ISO}" \
      '{
        hasCompletedOnboarding:   true,
        firstStartTime:           $now,
        installMethod:            "native",
        autoUpdates:              false,
        projects: {
          "/workspace": {
            hasTrustDialogAccepted:                  true,
            hasClaudeMdExternalIncludesApproved:     true,
            hasClaudeMdExternalIncludesWarningShown: true,
            # enableAllProjectMcpServers + enabledMcpjsonServers
            # pre-resolve the "New MCP server found in .mcp.json"
            # approval prompt. Belt-and-suspenders in case a future
            # CC version checks only one of the two keys.
            enableAllProjectMcpServers:              true,
            enabledMcpjsonServers:                   ["clawborrator"]
          }
        }
      }' > "${GLOBAL_CFG}"
    echo "[worker] seeded ${GLOBAL_CFG}"
  fi

  # API-key approval. With ANTHROPIC_API_KEY set, claude prompts
  # "Detected a custom API key in your environment, do you want to
  # use it?" (default: No) and remembers the answer in
  # customApiKeyResponses.approved as the key's LAST 20 CHARACTERS.
  # Seed that on every boot (idempotent merge, survives a rotated
  # key) so a headless worker never sits on the prompt. The expect
  # wrapper still answers it as a fallback.
  if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
    KEY_TAIL="$(printf '%s' "${ANTHROPIC_API_KEY}" | tail -c 20)"
    jq --arg k "${KEY_TAIL}" '
      .customApiKeyResponses.approved = ((.customApiKeyResponses.approved // []) + [$k] | unique)
      | .customApiKeyResponses.rejected = ((.customApiKeyResponses.rejected // []) - [$k])
    ' "${GLOBAL_CFG}" > "${GLOBAL_CFG}.tmp" && mv "${GLOBAL_CFG}.tmp" "${GLOBAL_CFG}"
    echo "[worker] pre-approved ANTHROPIC_API_KEY in ${GLOBAL_CFG} (customApiKeyResponses)"
  fi

  # settings.json is rewritten on every boot — it's env-driven
  # configuration (CLAUDE_SKIP_PERMISSIONS toggle takes effect on
  # restart), not state. Claude code doesn't mutate this file at
  # runtime, so overwriting is safe.
  SKIP_DANGEROUS=$([ "${CLAUDE_SKIP_PERMISSIONS:-0}" = "1" ] && echo true || echo false)
  jq -n \
    --argjson skipDangerous "${SKIP_DANGEROUS}" \
    '{
      theme:                              "dark",
      editorMode:                         "normal",
      skipAutoPermissionPrompt:           true,
      skipDangerousModePermissionPrompt:  $skipDangerous,
      permissions: {
        defaultMode: "auto"
      }
    }' > "${SETTINGS_FILE}"
  echo "[worker] wrote ${SETTINGS_FILE} (skipDangerous=${SKIP_DANGEROUS})"

  # Fix ownership before dropping privileges. Bind-mounted /workspace
  # may have arrived owned by some other uid (Docker creates the
  # bind-mount target as root if it didn't exist on the host); the
  # worker user needs to own it to write .mcp.json + run claude.
  chown -R "${WORKER_USER}:${WORKER_USER}" "${WORKER_HOME}"
  chown -R "${WORKER_USER}:${WORKER_USER}" /workspace

  # ─── Git safe.directory (system-wide) ─────────────────────────
  # Bind-mounted /workspace often has a uid mismatch between the
  # host's directory owner and the in-container worker user. Git's
  # "dubious ownership" guard then refuses to operate on any repo
  # under /workspace (clone, fetch, status — all blocked). Whitelist
  # all paths so any user in the container — `worker` (the agent),
  # `root` (operator `docker exec`-ing in to debug), or anyone else
  # — bypasses the check. --system writes /etc/gitconfig which root
  # can do here in Phase 1; doing it later as `worker` via --global
  # only fixes the worker user's own ~/.gitconfig.
  git config --system --add safe.directory '*'
  echo "[worker] git safe.directory: '*' (system-wide, /etc/gitconfig)"

  # ─── Docker socket access (optional — only if mounted) ─────────
  # If /var/run/docker.sock is mounted in, give the worker user
  # access. The socket arrives with whatever GID the host's docker
  # group uses (varies by platform), which won't match any group
  # the worker user is in by default. Solution: read the socket's
  # GID, create a matching group inside the container (or use any
  # existing group with that GID), add worker to it.
  #
  # The worker is added to the existing group whose GID matches —
  # if no group exists at that GID, we create one called
  # `docker_host`. This is the standard "Docker outside of Docker"
  # permission pattern.
  #
  # Skipping the socket mount entirely (the default for workers
  # that don't need to spawn) means this block silently no-ops.
  if [ -S /var/run/docker.sock ]; then
    SOCK_GID=$(stat -c '%g' /var/run/docker.sock)
    SOCK_GROUP=$(getent group "${SOCK_GID}" | cut -d: -f1 || true)
    if [ -z "${SOCK_GROUP}" ]; then
      groupadd --gid "${SOCK_GID}" docker_host
      SOCK_GROUP=docker_host
    fi
    usermod -aG "${SOCK_GROUP}" "${WORKER_USER}"
    echo "[worker] docker.sock detected (gid=${SOCK_GID}, group=${SOCK_GROUP}) — ${WORKER_USER} added"
  fi

  # Drop privileges via gosu. HOME is set explicitly so claude
  # finds the credentials we just wrote.
  export HOME="${WORKER_HOME}"
  exec gosu "${WORKER_USER}" "$0" "$@"
fi

# ════════════════════════════════════════════════════════════════
# Phase 2 — worker
# ════════════════════════════════════════════════════════════════

cd /workspace

# ─── Git identity ──────────────────────────────────────────────
# Without these, the first commit fails with "Please tell me who you
# are" and claude burns a turn running `git config user.email/name`
# itself. Cheap to set per-boot; lives in ~/.gitconfig (worker's
# HOME, not the persisted ~/.claude volume) so it always reflects
# the current env. Empty env → skip (and claude will see the friendly
# git error on the first commit, no harm).
if [ -n "${GIT_USER_EMAIL:-}" ]; then
  git config --global user.email "${GIT_USER_EMAIL}"
fi
if [ -n "${GIT_USER_NAME:-}" ]; then
  git config --global user.name  "${GIT_USER_NAME}"
fi
if [ -n "${GIT_USER_EMAIL:-}" ] || [ -n "${GIT_USER_NAME:-}" ]; then
  echo "[worker] git identity: ${GIT_USER_NAME:-(unset)} <${GIT_USER_EMAIL:-(unset)}>"
fi

# ─── Model selection ──────────────────────────────────────────
# MODEL accepts the friendly aliases opus | sonnet | haiku and
# translates to the explicit model ID via ANTHROPIC_MODEL. Anything
# else is passed through verbatim, so operators can pin to an
# exact version if they want. Default haiku — cheap fast model
# right for most worker-pool workloads.
#
# Export so claude (the child process) inherits ANTHROPIC_MODEL.
case "${MODEL:-haiku}" in
  opus)
    export ANTHROPIC_MODEL=claude-opus-4-7
    ;;
  sonnet)
    export ANTHROPIC_MODEL=claude-sonnet-4-6
    ;;
  haiku)
    export ANTHROPIC_MODEL=claude-haiku-4-5-20251001
    ;;
  "")
    export ANTHROPIC_MODEL=claude-haiku-4-5-20251001
    ;;
  *)
    # Pass through full IDs untouched (e.g., a future
    # `claude-opus-5-0` or a snapshot ID).
    export ANTHROPIC_MODEL="${MODEL}"
    ;;
esac
echo "[worker] model: ${MODEL:-haiku} (ANTHROPIC_MODEL=${ANTHROPIC_MODEL})"

# ─── Optional repo clone ─────────────────────────────────────────
# Claude's cwd is /workspace, NOT the cloned repo. We clone one
# level deeper into /workspace/${REPO_DIR_NAME:-repo} so the repo's
# working tree stays untouched by worker plumbing (.mcp.json, .claude/,
# CLAUDE.md all live at /workspace/, not inside the repo). Trade-off:
# `git status` from claude's cwd fails — operator/claude has to
# `cd repo` or use `git -C repo …`. The /workspace/CLAUDE.md note
# written below orients claude to this layout.
#
# Only clones if REPO_URL is set AND the target dir doesn't already
# have a .git directory. On second+ boots the existing checkout is
# reused and brought up to date per REPO_SYNC (see below) so the
# latest playbook on the remote is what runs. "docker restart picks up
# the latest CLAUDE.md" is the contract.
#
# REPO_SYNC=rebase (default): `git pull --rebase`. Preserves local
# commits, for workers (engager, cloud-chaser) that commit their own
# activity output (audit JSON, snapshots) into the repo every cycle —
# a hard reset would discard those. The catch: rebase refuses on a
# dirty tree and used to SILENTLY continue on the stale playbook. Two
# hardenings: (1) `core.fileMode false` so a playbook's boot-time
# `chmod +x` on tracked scripts no longer dirties the tree (the real-
# world trap — a monitor was stuck 4 commits behind because of it);
# (2) a failed pull now logs a LOUD `!! RUNNING STALE PLAYBOOK` to
# stderr instead of a quiet "continuing".
#
# REPO_SYNC=reset: `git fetch` + `git reset --hard origin/<ref>` +
# `git clean -fd`. Always lands on the remote tip. For workers that
# NEVER commit into their repo (monitors, routers — state lives in
# /workspace/memory + /workspace/snapshots). Unwedgeable; the right
# choice for any read-only-repo worker.
REPO_DIR="/workspace/${REPO_DIR_NAME:-repo}"
if [ -n "${REPO_URL:-}" ]; then
  if [ -d "${REPO_DIR}/.git" ]; then
    # Ignore executable-bit-only diffs. A playbook's boot-time `chmod +x`
    # on tracked scripts (committed 100644) would otherwise dirty the
    # tree, make the update below fail, and silently pin the worker to a
    # STALE playbook across every restart. core.fileMode=false makes git
    # blind to mode changes so this can't happen.
    git -C "${REPO_DIR}" config core.fileMode false 2>/dev/null || true

    # REPO_SYNC selects how an existing checkout is brought up to date:
    #   rebase (default) — git pull --rebase; preserves local commits,
    #     for workers that commit their own output into the repo
    #     (engager, cloud-chaser).
    #   reset — git fetch + git reset --hard origin/<ref>; always lands
    #     on the remote tip. For workers that NEVER commit into their
    #     repo (monitors, routers — they write state to /workspace/memory
    #     and /workspace/snapshots, not /workspace/repo). Immune to a
    #     dirty tree or divergence wedging the update.
    if [ "${REPO_SYNC:-rebase}" = "reset" ]; then
      echo "[worker] ${REPO_DIR} exists — hard-sync to origin (REPO_SYNC=reset)"
      if git -C "${REPO_DIR}" fetch origin --quiet 2>&1; then
        if [ -n "${REPO_REF:-}" ]; then
          RESET_TARGET="origin/${REPO_REF}"
        else
          RESET_TARGET="$(git -C "${REPO_DIR}" rev-parse --abbrev-ref --symbolic-full-name '@{u}' 2>/dev/null || echo '')"
        fi
        if [ -n "${RESET_TARGET}" ] && git -C "${REPO_DIR}" reset --hard "${RESET_TARGET}" 2>&1; then
          git -C "${REPO_DIR}" clean -fd 2>&1 || true
          echo "[worker] hard-synced ${REPO_DIR} to ${RESET_TARGET}"
        else
          echo "[worker] !! REPO_SYNC=reset could not reset ${REPO_DIR} to '${RESET_TARGET:-<no upstream>}' — RUNNING STALE PLAYBOOK" >&2
        fi
      else
        echo "[worker] !! REPO_SYNC=reset fetch failed — RUNNING STALE PLAYBOOK (check REPO_PAT / network)" >&2
      fi
    else
      echo "[worker] ${REPO_DIR} exists — pulling latest (rebase)"
      if git -C "${REPO_DIR}" pull --rebase 2>&1; then
        if [ -n "${REPO_REF:-}" ]; then
          echo "[worker] re-checking out ref ${REPO_REF} after pull"
          git -C "${REPO_DIR}" checkout "${REPO_REF}" || \
            echo "[worker] ref ${REPO_REF} not found — staying on default branch"
        fi
      else
        git -C "${REPO_DIR}" rebase --abort 2>/dev/null || true
        # LOUD, not the old quiet "continuing" — a stale playbook is a
        # real failure, not a no-op. Workers that don't commit into their
        # repo should set REPO_SYNC=reset to make updates unwedgeable.
        echo "[worker] !! git pull --rebase failed — RUNNING STALE PLAYBOOK. Likely a dirty tree or local commits. Set REPO_SYNC=reset for workers that don't commit into their repo." >&2
      fi
    fi
  else
    # Splice PAT into the URL if one was supplied. We rewrite into
    # https://<user>:<pat>@<host>/<path>. The full credentialed URL
    # is what `git clone` actually uses; we only echo the redacted
    # form so the PAT doesn't end up in `docker logs`. It DOES still
    # land in ${REPO_DIR}/.git/config after clone (so subsequent
    # fetch/push from inside CC keep working) — see .env.example
    # for the security caveat.
    EFFECTIVE_REPO_URL="${REPO_URL}"
    if [ -n "${REPO_PAT:-}" ]; then
      case "${REPO_URL}" in
        https://*)
          host_path="${REPO_URL#https://}"
          EFFECTIVE_REPO_URL="https://${REPO_PAT_USER:-x-access-token}:${REPO_PAT}@${host_path}"
          echo "[worker] cloning ${REPO_URL} into ${REPO_DIR} (PAT spliced)"
          ;;
        *)
          echo "[worker] REPO_PAT set but REPO_URL is not https:// — cloning without credentials"
          echo "[worker] cloning ${REPO_URL} into ${REPO_DIR}"
          ;;
      esac
    else
      echo "[worker] cloning ${REPO_URL} into ${REPO_DIR}"
    fi
    # `git clone … <target>` creates the target dir; ensure parent
    # exists and is writable.
    mkdir -p "$(dirname "${REPO_DIR}")"
    # Don't `set -e`-exit on a missing ref — that's a recoverable
    # state (e.g., empty repo with no main yet); just warn.
    if ! git clone "${EFFECTIVE_REPO_URL}" "${REPO_DIR}"; then
      echo "[worker] git clone failed — continuing without a repo (you can clone manually inside the container)"
    else
      # Blind git to executable-bit changes from the start so a boot-time
      # `chmod +x` never dirties the tree (see the reuse path above).
      git -C "${REPO_DIR}" config core.fileMode false 2>/dev/null || true
      if [ -n "${REPO_REF:-}" ]; then
        echo "[worker] checking out ref ${REPO_REF}"
        git -C "${REPO_DIR}" checkout "${REPO_REF}" || \
          echo "[worker] ref ${REPO_REF} not found — staying on default branch"
      fi
    fi
  fi
fi

# ─── Orient claude to the /workspace layout ──────────────────────
# /workspace/CLAUDE.md tells claude "the codebase is in ./repo —
# don't touch .mcp.json or .claude/ here, those are worker plumbing."
# Written on every boot since it's a static reference, but only if
# absent so the operator can override by writing their own.
CLAUDE_MD="/workspace/CLAUDE.md"
if [ ! -f "${CLAUDE_MD}" ]; then
  REPO_DIR_REL="${REPO_DIR_NAME:-repo}"
  cat > "${CLAUDE_MD}" <<EOF
# Worker container layout

You are running inside a clawborrator worker_v1 docker container.
Your current working directory is \`/workspace\`, but **the actual
codebase you are here to work on is in \`./${REPO_DIR_REL}/\`**.

For most operations:

- \`cd ${REPO_DIR_REL}\` first, or use \`git -C ${REPO_DIR_REL} …\`
- Reference repo files as \`${REPO_DIR_REL}/path/to/file\` from
  this cwd, or as relative paths after \`cd\`-ing in.

Files at the \`/workspace/\` level are worker plumbing and should
not be modified or committed anywhere:

- \`.mcp.json\` — clawborrator MCP server config.
- \`.claude/\` — project-level hooks, settings.local, MCP plugin state.
- \`CLAUDE.md\` — this file.

Anything under \`/workspace/${REPO_DIR_REL}/\` is fair game and is
what the operator expects you to read, edit, and commit.

## Spawning sibling workers (swarm pattern)

If \`docker --version\` works in your Bash tool, this container has
the Docker socket mounted and you can spawn sibling worker containers
on the same Docker host. Use the helper scripts (preferred) — they
inherit credentials and config from this worker's env so you don't
have to remember the docker run incantation:

\`\`\`bash
# Spawn one sibling to do a specific subtask:
spawn-worker --role "test-writer-foo" \\
             --initial-prompt "Write a Jest test for ${REPO_DIR_REL}/src/components/Foo.tsx. Commit on branch test-foo. Reply when done."
# → SPAWN_OK container=worker-test-writer-foo-1747059823 routing=@workspace-2626a003

# The child shows up in mcp__clawborrator__list_peers under that routing name
# within ~10–15s. Dispatch work to it with mcp__clawborrator__route_to_peer.

# Clean up when done:
terminate-worker @workspace-2626a003           # by routing name
terminate-worker worker-test-writer-foo-…      # OR by container name
\`\`\`

\`spawn-worker --help\` shows the full flag set. By default each child
inherits the SAME repo, credentials, and hub config as this worker.
Override per-child with \`--repo-url\`, \`--repo-ref\`, \`--no-clone\`,
\`--env KEY=VAL\` (repeatable), \`--wait <seconds>\`.

**When to use the swarm pattern:**
- The task naturally parallelizes (N independent files, N repos, N branches).
- You want a child to operate in a sandboxed copy without polluting your own context.
- A subtask is expensive enough that running it in parallel saves wall-clock time.

**When NOT to use:**
- The task is small enough to do here directly — spawning is ~15s overhead per child + Docker memory cost.
- You're not sure exactly what the children should do — spawn workers with vague prompts and they'll burn quota idling.
- You only need a one-off answer — \`mcp__clawborrator__probe_peers\` against existing peers is cheaper.

**Patterns that work well:**
- Fan-out: \`for f in ./files; do spawn-worker --role "process-\$f" --initial-prompt "do X to \$f"; done\` — then aggregate via peer reports.
- Cap-in-flight: before each new spawn, check \`list_peers\` and only spawn if active children < cap.
- Self-cleanup: instruct each child to commit + push + exit on completion; you watch for the peer report and call \`terminate-worker\`.

If you spawn workers and run out of work, kill them — every running child is consuming Anthropic quota.
EOF
  echo "[worker] wrote ${CLAUDE_MD}"
fi

# ─── Optional clawborrator integration ───────────────────────────
HUB_URL="${CLAWBORRATOR_HUB_URL:-wss://next.clawborrator.com}"
FLAGS=""
if [ -n "${CLAWBORRATOR_TOKEN:-}" ]; then
  echo "[worker] writing .mcp.json — clawborrator hub=${HUB_URL}"
  # Invoke the globally-installed bin directly (npm install -g lands
  # it at /usr/local/bin/clawborrator-mcp via the package's bin field).
  # Bypasses npx -y, which on container recreate has an empty cache
  # and races claude-code's MCP startup timeout when paired with other
  # cold-spawning MCP servers in the same .mcp.json.
  jq -n \
    --arg hub  "${HUB_URL}" \
    --arg tok  "${CLAWBORRATOR_TOKEN}" \
    '{
      mcpServers: {
        clawborrator: {
          command: "clawborrator-mcp",
          args:    [],
          env: {
            CLAWBORRATOR_HUB_URL: $hub,
            CLAWBORRATOR_TOKEN:   $tok
          }
        }
      }
    }' > .mcp.json
  chmod 600 .mcp.json

  # ─── Optional repo-side .mcp.json merge ───────────────────────
  # Specialist playbooks can ship a .mcp.json at the repo root
  # listing additional MCP servers (e.g. Google Drive, Salesforce,
  # internal tooling). Merge those entries into /workspace/.mcp.json
  # so claude sees them at boot. Worker's clawborrator entry wins
  # on key collision — the repo can't accidentally clobber the
  # token-bearing channel connection.
  REPO_DIR_REL="${REPO_DIR_NAME:-repo}"
  REPO_MCP="/workspace/${REPO_DIR_REL}/.mcp.json"
  if [ -f "${REPO_MCP}" ]; then
    echo "[worker] merging repo-side .mcp.json from ${REPO_DIR_REL}/"
    if jq -n \
        --slurpfile repo "${REPO_MCP}" \
        --slurpfile core /workspace/.mcp.json \
        '{ mcpServers: (($repo[0].mcpServers // {}) + ($core[0].mcpServers // {})) }' \
        > /workspace/.mcp.json.merged 2>/tmp/mcp-merge-err; then
      mv /workspace/.mcp.json.merged /workspace/.mcp.json
      chmod 600 /workspace/.mcp.json
      # Count merged keys for the boot log so operators can spot
      # silent drops (e.g. malformed entries that jq skipped).
      EXTRA_KEYS=$(jq -r '.mcpServers | keys[] | select(. != "clawborrator")' /workspace/.mcp.json | tr '\n' ',' | sed 's/,$//')
      echo "[worker] merged MCP servers: ${EXTRA_KEYS:-<none>}"
    else
      echo "[worker] WARN: failed to merge repo .mcp.json; keeping clawborrator-only config:"
      cat /tmp/mcp-merge-err
      rm -f /workspace/.mcp.json.merged
    fi
  fi

  # ─── Env substitution on the final .mcp.json ──────────────────
  # Specialist .mcp.json files can reference env vars via the
  # standard ${VAR} syntax — useful for API keys passed via the
  # worker's .env (so secrets don't sit in the repo). Unset vars
  # are left untouched so a literal "${not-an-env-var}" stays as
  # written. Only matches ${UPPERCASE_UNDERSCORE} to avoid
  # accidentally substituting unrelated placeholder syntax.
  node <<'MCP_ENVSUB'
const fs = require('fs');
const path = '/workspace/.mcp.json';
const src = fs.readFileSync(path, 'utf8');
const out = src.replace(/\$\{([A-Z_][A-Z0-9_]*)\}/g, (m, n) =>
  process.env[n] !== undefined ? process.env[n] : m);
if (out !== src) {
  fs.writeFileSync(path, out);
  console.log('[worker] applied env substitution to .mcp.json');
}
MCP_ENVSUB
  chmod 600 /workspace/.mcp.json

  # --dangerously-load-development-channels enables in-band channel
  # notifications (`<channel source="..." chat_id="…">` tags showing
  # up inline in Claude's context). The non-dangerous --channels
  # flag connects the WS but doesn't surface inbound prompts to
  # claude, so routed prompts from the hub silently disappear.
  # The dangerously flag triggers a startup prompt; we accept it
  # via the expect wrapper (USE_EXPECT_WRAPPER=1 below).
  FLAGS="${FLAGS} --dangerously-load-development-channels server:clawborrator"
  USE_EXPECT_WRAPPER=1
fi

# ─── Permission mode ─────────────────────────────────────────────
if [ "${CLAUDE_SKIP_PERMISSIONS:-0}" = "1" ]; then
  FLAGS="${FLAGS} --dangerously-skip-permissions"
fi

# When ANTHROPIC_API_KEY is set, claude shows a "Do you want to use
# this API key?" prompt with default = "No (recommended)". A
# headless worker can't answer it, so we use the expect wrapper
# (it handles BOTH the API-key prompt and the dev-channels one).
if [ -n "${ANTHROPIC_API_KEY:-}" ]; then
  USE_EXPECT_WRAPPER=1
fi

# ─── Launch ──────────────────────────────────────────────────────
# Wrap claude in the expect script when there are startup prompts
# we need to auto-dismiss (dev-channels warning, API-key approval).
# Standalone OAuth runs without clawborrator skip the wrapper since
# there's no prompt to dismiss.
#
# Override: DISABLE_AUTOENTER=1 forces the bare `claude` launcher
# even when prompts will fire. Use when you plan to `docker attach`
# and answer the prompts yourself (e.g., to drive `/login`
# interactively, pick "No (recommended)" on the API-key prompt to
# get a fresh OAuth flow, etc.).
if [ "${DISABLE_AUTOENTER:-0}" = "1" ]; then
  LAUNCHER="claude"
  echo "[worker] DISABLE_AUTOENTER=1 — skipping expect wrapper, you'll need to dismiss any startup prompts via docker attach"
elif [ "${USE_EXPECT_WRAPPER:-0}" = "1" ]; then
  LAUNCHER="/usr/local/bin/claude-with-autoenter.expect"
else
  LAUNCHER="claude"
fi

# ─── network-ready gate ───────────────────────────────────────────
# Block until the clawborrator hub is reachable before spawning
# claude. Docker's restart policy (unless-stopped) launches the
# container as soon as docker-engine is up after a host reboot —
# which can be seconds before systemd-resolved or routing tables
# are stable. Without this gate, claude-code spawns MCP servers
# against a not-yet-routable hub, the MCP clients fail-fast into
# a silent-dead state, and the container stays "up" with no
# working MCPs until manual restart. Bounded wait (~120s),
# non-fatal — if the hub stays unreachable we proceed anyway and
# let the application surface the error.
if [ -n "${CLAWBORRATOR_HUB_URL:-}" ]; then
  hub_http="$(echo "${CLAWBORRATOR_HUB_URL}" | sed 's|^ws|http|')/healthz"
  for attempt in $(seq 1 60); do
    if curl -sS -m 3 "${hub_http}" >/dev/null 2>&1; then
      [ "$attempt" -gt 1 ] && echo "[worker] hub reachable on attempt $attempt (${hub_http})"
      break
    fi
    if [ "$attempt" -eq 60 ]; then
      echo "[worker] WARN: hub still unreachable after 120s (${hub_http}); spawning claude anyway"
    else
      [ "$attempt" -eq 1 ] && echo "[worker] waiting for hub reachability (${hub_http})..."
      sleep 2
    fi
  done
fi

if [ -n "${CLAUDE_INITIAL_PROMPT:-}" ]; then
  echo "[worker] launching ${LAUNCHER} with initial prompt (${#CLAUDE_INITIAL_PROMPT} chars)"
  # shellcheck disable=SC2086  # FLAGS is intentionally word-split
  exec "${LAUNCHER}" ${FLAGS} "$@" "${CLAUDE_INITIAL_PROMPT}"
fi

echo "[worker] launching ${LAUNCHER} in /workspace"
# shellcheck disable=SC2086  # FLAGS is intentionally word-split
exec "${LAUNCHER}" ${FLAGS} "$@"
